# Generated by Django 3.1.7 on 2021-04-08 04:57

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
    ]
